SET ECHO OFF
SET VERIFY OFF
SET HEADING OFF

-- LONG RAW -> BLOB
ALTER TABLE T_SERVICEPROTOCL MODIFY(C_PROTOCLCONTAIN BLOB);
-- LONG RAW -> BLOB
ALTER TABLE T_UPT_FILECONTAIN MODIFY(C_CONTAIN BLOB);
-- LONG -> INTEGER
ALTER TABLE PLAN_TABLE MODIFY(OTHER INTEGER);
-- LONG RAW -> BLOB
ALTER TABLE T_EQUIPMENT MODIFY(C_EQUPICTURE BLOB);
-- LONG RAW -> BLOB
ALTER TABLE T_MAINTAINREQUIREMENT MODIFY(C_MAINTAINREQUIREMENTCONTAIN BLOB);