SET ECHO OFF
SET VERIFY OFF
SET HEADING OFF

SELECT * FROM T_PERSONAL WHERE C_NATIVE IS NOT NULL AND C_NATIVE <> '';
SELECT LENGTH(C_NATIVE), COUNT(*) FROM T_PERSONAL GROUP BY LENGTH(C_NATIVE);
SELECT * FROM T_PERSONAL WHERE C_BANKCARD IS NOT NULL AND C_BANKCARD <> '';
SELECT LENGTH(C_BANKCARD), COUNT(*) FROM T_PERSONAL GROUP BY LENGTH(C_BANKCARD);
