SET ECHO OFF
SET VERIFY OFF
SET HEADING OFF

ALTER TABLE T_PERSONAL ADD (C_UPGRADE_REASON  VARCHAR2(128));
ALTER TABLE T_PERSONAL ADD (C_ALLOTREASON  VARCHAR2(128));
ALTER TABLE T_PERSONAL ADD (C_RETIREDATE  DATE);
ALTER TABLE T_PERSONAL ADD (C_CONTRACTREASON  VARCHAR2(128));
ALTER TABLE T_PERSONAL ADD (C_LASTMODIFIER  NUMBER(18));
