SET ECHO OFF
SET VERIFY OFF
SET HEADING OFF

CREATE OR REPLACE TRIGGER TRG_PERSONALID
BEFORE INSERT ON T_PERSONAL
FOR EACH ROW
DECLARE NEXT_ID NUMBER;
BEGIN
	SELECT SEQ_PERSONAL.NEXTVAL INTO NEXT_ID FROM T_SEQFRO;
	:NEW.C_PERSONALID := NEXT_ID;
END;
/