--人员业务调动表(新)
EXEC SP_DROPTABLE('T_PSN_ONLINE');
CREATE TABLE T_PSN_ONLINE
(
  C_BELONG       NUMBER(18)                         NULL,
  C_PERSON       NUMBER(18)                         NULL,
  C_ALLOTREASON  VARCHAR2(20 BYTE)                  NULL,
  C_DEPART       NUMBER(18)                     NOT NULL,
  C_OFFICE       VARCHAR2(40 BYTE)                  NULL,
  C_LINEID       NUMBER(18)                         NULL,
  C_BUSID        NUMBER(18)                         NULL,
  C_ONDATE       DATE                           NOT NULL,
  C_DOWNDATE     DATE                           NOT NULL,
  C_ALLOTER      VARCHAR2(30 BYTE)              NOT NULL
) LOGGING NOCACHE NOPARALLEL MONITORING;
--关键字
ALTER TABLE T_PSN_ONLINE ADD (CONSTRAINT PK_HRPSN_ONLINE PRIMARY KEY (C_BELONG, C_PERSON, C_ONDATE));
--人员外键
ALTER TABLE T_PSN_ONLINE ADD (CONSTRAINT FK_HRPSN_ONLINE FOREIGN KEY (C_BELONG, C_PERSON) REFERENCES T_PERSONAL (C_BELONG,C_PERSONALID));
--按人员索引
CREATE INDEX IDX_PSN_ONLINE ON T_PSN_ONLINE (C_BELONG, C_PERSON) LOGGING NOPARALLEL;