SET ECHO OFF
SET VERIFY OFF
SET HEADING OFF

EXEC SP_DROPTABLE('T_HRSAL_ITEM');

CREATE TABLE T_HRSAL_ITEM
(
  C_BELONG          NUMBER(18)                  NOT NULL,
  C_ID              NUMBER(18)                  NOT NULL,
  C_NO              VARCHAR2(16 BYTE)           NOT NULL,
  C_NAME            VARCHAR2(30 BYTE)           NOT NULL,
  C_ONDATE          DATE                        NOT NULL,
  C_DOWNDATE        DATE                        NOT NULL,
  C_ACCOUNT_DEBIT   VARCHAR2(30 BYTE)               NULL,
  C_ACCOUNT_CREDIT  VARCHAR2(30 BYTE)               NULL,
  C_FLAG            NUMBER(1)                   NOT NULL,
  C_TYPE            VARCHAR2(4 BYTE)            NOT NULL
) LOGGING NOCACHE NOPARALLEL MONITORING;

COMMENT ON COLUMN T_HRSAL_ITEM.C_TYPE IS '固定类别：工资项目（WG）、社保项目（SG）、福利项目（WF）、代扣项目（DK）、对消项目（平帐项目PZ）';

CREATE INDEX IDX_HRSAL_ITEM ON T_HRSAL_ITEM (C_BELONG) LOGGING NOPARALLEL;
CREATE UNIQUE INDEX IDX_HRSAL_ITEMID ON T_HRSAL_ITEM (C_ID) LOGGING NOPARALLEL;
CREATE UNIQUE INDEX IDX_HRSAL_ITEMNO ON T_HRSAL_ITEM (C_BELONG, C_NO) LOGGING NOPARALLEL;
ALTER TABLE T_HRSAL_ITEM ADD (CONSTRAINT CHK_HRSAL_ITEM_TYPE CHECK (C_TYPE IN ('WG','SG','WF','DK','PZ')));
ALTER TABLE T_HRSAL_ITEM ADD (CONSTRAINT PK_HRSAL_ITEM PRIMARY KEY (C_BELONG, C_ID));
ALTER TABLE T_HRSAL_ITEM ADD (CONSTRAINT FK_HRSAL_ITEM FOREIGN KEY (C_BELONG) REFERENCES T_BRANCH (C_BRANCHID));

EXEC SP_DROPSEQ('SEQ_HRSAL_ITEM');
CREATE SEQUENCE SEQ_HRSAL_ITEM START WITH 1 MAXVALUE 999999999999999999999999999 MINVALUE 1 NOCYCLE NOCACHE NOORDER;

CREATE OR REPLACE TRIGGER TRG_HRSAL_ITEMID
BEFORE INSERT ON T_HRSAL_ITEM
FOR EACH ROW
DECLARE NEXT_ID NUMBER;
BEGIN
  SELECT SEQ_HRSAL_ITEM.NEXTVAL INTO NEXT_ID FROM T_SEQFRO;
  :NEW.C_ID := NEXT_ID;
END;
/