SET ECHO OFF
SET VERIFY OFF
SET HEADING OFF

EXEC SP_DROPTABLE('T_HRSAL_DEPTPSN');

CREATE TABLE T_HRSAL_DEPTPSN
(
  C_BELONG    NUMBER(18)                        NOT NULL,
  C_DEPART    NUMBER(18)                        NOT NULL,
  C_PERSON    NUMBER(18)                        NOT NULL,
  C_BANK      VARCHAR2(30 BYTE)                     NULL,
  C_BANKCARD  VARCHAR2(30 BYTE)                     NULL,
  C_COMMENT   VARCHAR2(255 BYTE)                    NULL
) LOGGING NOCACHE NOPARALLEL MONITORING;

COMMENT ON TABLE T_HRSAL_DEPTPSN IS '一个人可以在多个部门领取工资 
IDX_HRSAL_DEPTPSND: 查看一个部门下领工资的人员 
IDX_HRSAL_DEPTPSNP: 查看一个人在哪些部门领取工资';


CREATE INDEX IDX_HRSAL_DEPTPSND ON T_HRSAL_DEPTPSN (C_BELONG, C_DEPART) LOGGING NOPARALLEL;
ALTER TABLE T_HRSAL_DEPTPSN ADD (CONSTRAINT PK_HRSAL_DEPTPSN PRIMARY KEY (C_BELONG, C_DEPART, C_PERSON));
ALTER TABLE T_HRSAL_DEPTPSN ADD (CONSTRAINT FK_HRSAL_DEPTPSN_DEPT FOREIGN KEY (C_BELONG, C_DEPART) REFERENCES T_DEPARTMENT (C_BELONG,C_DEPARTMENTID));
ALTER TABLE T_HRSAL_DEPTPSN ADD (CONSTRAINT FK_HRSAL_DEPTPSN_PSN FOREIGN KEY (C_BELONG, C_PERSON) REFERENCES T_PERSONAL (C_BELONG,C_PERSONALID));