SET ECHO OFF
SET VERIFY OFF
SET HEADING OFF

EXEC SP_DROPTABLE('T_HRSAL_FACTHD');

CREATE TABLE T_HRSAL_FACTHD
(
  C_BELONG     NUMBER(18)                       NOT NULL,
  C_NO         VARCHAR2(30 BYTE)                NOT NULL,
  C_DEPART     NUMBER(18)                       NOT NULL,
  C_ISSUEDATE  DATE                             NOT NULL,
  C_ISSUETYPE  VARCHAR2(1 BYTE)                 NOT NULL,
  C_SUMMARY    VARCHAR2(255 BYTE)                   NULL,
  C_ISSUEBY    NUMBER(18)                       NOT NULL,
  C_COMMENT    VARCHAR2(255 BYTE)                   NULL
) LOGGING NOCACHE NOPARALLEL MONITORING;
COMMENT ON COLUMN T_HRSAL_FACTHD.C_ISSUETYPE IS 'ÏÖ£¨C£©£¬×ª£¨T£©£¬Îï£¨G£©';

CREATE UNIQUE INDEX IDX_HRSAL_FACTHDNO ON T_HRSAL_FACTHD (C_NO) LOGGING NOPARALLEL;
CREATE INDEX IDX_HRSAL_FACTHD_DEPT ON T_HRSAL_FACTHD (C_BELONG, C_DEPART) LOGGING NOPARALLEL;
ALTER TABLE T_HRSAL_FACTHD ADD (CONSTRAINT CHK_HRSAL_FACTHD_TYPE CHECK (C_ISSUETYPE IN ('C','T','G')));
ALTER TABLE T_HRSAL_FACTHD ADD (CONSTRAINT PK_HRSAL_FACTHD PRIMARY KEY (C_BELONG, C_NO));
ALTER TABLE T_HRSAL_FACTHD ADD (CONSTRAINT FK_HRSAL_FACTHD_DEPT FOREIGN KEY (C_BELONG, C_DEPART) REFERENCES T_DEPARTMENT (C_BELONG,C_DEPARTMENTID));