SET ECHO OFF
SET VERIFY OFF
SET HEADING OFF

EXEC SP_DROPTABLE('T_HRSAL_FACTDT');

CREATE TABLE T_HRSAL_FACTDT
(
  C_BELONG   NUMBER(18)                         NOT NULL,
  C_HDNO     VARCHAR2(30 BYTE)                  NOT NULL,
  C_PERSON   NUMBER(18)                         NOT NULL,
  C_ITEM     NUMBER(18)                         NOT NULL,
  C_AMOUNT  NUMBER(18,2)                        NOT NULL
) LOGGING NOCACHE NOPARALLEL MONITORING;

CREATE INDEX IDX_HRSAL_FACTDT_HDNO ON T_HRSAL_FACTDT (C_BELONG, C_HDNO) LOGGING NOPARALLEL;
CREATE INDEX IDX_HRSAL_FACTDT_PSN ON T_HRSAL_FACTDT (C_BELONG, C_HDNO, C_PERSON) LOGGING NOPARALLEL;
CREATE INDEX IDX_HRSAL_FACTDT_ITEM ON T_HRSAL_FACTDT (C_BELONG, C_HDNO, C_ITEM) LOGGING NOPARALLEL;
ALTER TABLE T_HRSAL_FACTDT ADD (CONSTRAINT PK_HRSAL_FACTDT PRIMARY KEY (C_BELONG, C_HDNO, C_PERSON, C_ITEM));
ALTER TABLE T_HRSAL_FACTDT ADD (CONSTRAINT FK_HRSAL_FACTDT_ITEM FOREIGN KEY (C_BELONG, C_ITEM) REFERENCES T_HRSAL_ITEM (C_BELONG,C_ID));
ALTER TABLE T_HRSAL_FACTDT ADD (CONSTRAINT FK_HRSAL_FACTDT_NO FOREIGN KEY (C_BELONG, C_HDNO) REFERENCES T_HRSAL_FACTHD (C_BELONG,C_NO));
ALTER TABLE T_HRSAL_FACTDT ADD (CONSTRAINT FK_HRSAL_FACTDT_PSN FOREIGN KEY (C_BELONG, C_PERSON) REFERENCES T_PERSONAL (C_BELONG,C_PERSONALID));