--人员照片表(新)
EXEC SP_DROPTABLE('T_PSN_PHOTO');
CREATE TABLE T_PSN_PHOTO
(
  C_BELONG     NUMBER(18)                       NOT NULL,
  C_PERSONALID NUMBER(18)                       NOT NULL,
  C_PHOTO      BLOB                             NOT NULL,
  C_PHOTODATE  DATE                             DEFAULT SYSDATE               NOT NULL,
  C_UPLOADBY   NUMBER(18)
) LOGGING NOCACHE NOPARALLEL NOMONITORING;
--关键字
ALTER TABLE T_PSN_PHOTO ADD (CONSTRAINT PK_PSN_PHOTO PRIMARY KEY (C_BELONG, C_PERSONALID));
--人员外键
ALTER TABLE T_PSN_PHOTO ADD (CONSTRAINT FK_PSN_PHOTO FOREIGN KEY (C_BELONG, C_PERSONALID) REFERENCES T_PERSONAL (C_BELONG,C_PERSONALID));
--照片上传人外键
ALTER TABLE T_PSN_PHOTO ADD (CONSTRAINT FK_PSN_PHOTO_UPLOADER FOREIGN KEY (C_BELONG, C_UPLOADBY) REFERENCES T_PERSONAL (C_BELONG,C_PERSONALID));