SET ECHO OFF
SET VERIFY OFF
SET HEADING OFF

--考勤组表
--原表名
EXEC SP_DROPTABLE('T_HRCHK_DEPTTERM_PSN');
--新表名
EXEC SP_DROPTABLE('T_HRCHK_GROUP');
CREATE TABLE T_HRCHK_GROUP
(
  C_BELONG    NUMBER(18)                        NOT NULL,
  C_ID        NUMBER(18)                        NOT NULL,
  C_NO        VARCHAR2(6)                       NOT NULL, /*考勤组编号*/
  C_NAME      VARCHAR2(40)                      NOT NULL, /*考勤组名称*/
  C_DEPART    NUMBER(18)                        NOT NULL, /*考勤组管理部门*/
  C_COMMENT   VARCHAR2(255 BYTE)                NULL
) LOGGING NOCACHE NOPARALLEL MONITORING;

--关键字内部ID
ALTER TABLE T_HRCHK_GROUP ADD (CONSTRAINT PK_HRCHK_GROUP PRIMARY KEY (C_BELONG, C_ID));
--管理部门外键
ALTER TABLE T_HRCHK_GROUP ADD (CONSTRAINT FK_HRCHK_GROUP_DEPT FOREIGN KEY (C_BELONG, C_DEPART) REFERENCES T_DEPARTMENT (C_BELONG,C_DEPARTMENTID));
--编号唯一
CREATE UNIQUE INDEX IDX_HRCHK_GROUP ON T_HRCHK_GROUP (C_BELONG, C_NO) LOGGING NOPARALLEL;
--内部ID序列
EXEC SP_DROPSEQ('SEQ_HRCHK_GROUP');
CREATE SEQUENCE SEQ_HRCHK_GROUP START WITH 1 MAXVALUE 999999999999999999999999999 MINVALUE 1 NOCYCLE NOCACHE NOORDER;
CREATE OR REPLACE TRIGGER TRG_HRCHK_GROUPID
BEFORE INSERT ON T_HRCHK_GROUP
FOR EACH ROW
DECLARE NEXT_ID NUMBER;
BEGIN
  SELECT SEQ_HRCHK_GROUP.NEXTVAL INTO NEXT_ID FROM T_SEQFRO;
  :NEW.C_ID := NEXT_ID;
END;
/
