SET ECHO OFF
SET VERIFY OFF
SET HEADING OFF

--长期休假计划(请假单)
EXEC SP_DROPTABLE('T_HRCHK_LONGPLAN');
CREATE TABLE T_HRCHK_LONGPLAN
(
  C_BELONG    NUMBER(18)                      NOT NULL,
  C_NO        VARCHAR(16)                     NOT NULL, /*请假单号码*/
  C_PERSON    NUMBER(18)                      NOT NULL, /*请假人*/
  C_FROMDATE  DATE                            NOT NULL, /*起始日期*/
  C_ENDDATE   DATE                            NOT NULL, /*终止日期*/
  C_HLDAY     NUMBER(18)                      NOT NULL, /*休假项目*/
  C_CHECKER   NUMBER(18)                      NOT NULL, /*批准人*/
  C_CHECKDATE DATE                            NOT NULL, /*批准日期*/
  C_CHECKDSP  VARCHAR(255)                    NULL      /*批准描述*/
) LOGGING NOCACHE NOPARALLEL NOMONITORING;
--关键字
ALTER TABLE T_HRCHK_LONGPLAN ADD (CONSTRAINT PK_HRCHK_LONGPLAN PRIMARY KEY (C_BELONG, C_NO));
--验证人同时段不能重复
--外键
ALTER TABLE T_HRCHK_LONGPLAN ADD (CONSTRAINT FK_HRCHKLONGPLAN_BRANCH FOREIGN KEY (C_BELONG) REFERENCES T_BRANCH (C_BRANCHID));
ALTER TABLE T_HRCHK_LONGPLAN ADD (CONSTRAINT FK_HRCHKLONGPLAN_PSN FOREIGN KEY (C_BELONG, C_PERSON) REFERENCES T_PERSONAL (C_BELONG,C_PERSONALID));
ALTER TABLE T_HRCHK_LONGPLAN ADD (CONSTRAINT FK_HRCHKLONGPLAN_HLDAY FOREIGN KEY (C_BELONG, C_HLDAY) REFERENCES T_HRCHK_HLDAY (C_BELONG,C_ID));
ALTER TABLE T_HRCHK_LONGPLAN ADD (CONSTRAINT FK_HRCHKLONGPLAN_CHK FOREIGN KEY (C_BELONG, C_CHECKER) REFERENCES T_PERSONAL (C_BELONG,C_PERSONALID));
