SET ECHO OFF
SET VERIFY OFF
SET HEADING OFF

--出勤计划表凭证头
EXEC SP_DROPTABLE('T_HRCHK_PLAN');
CREATE TABLE T_HRCHK_PLAN
(
  C_BELONG    NUMBER(18)          NOT NULL,
  C_NO        VARCHAR2(30 BYTE)   NOT NULL,   /*凭证号*/
  C_DATE      DATE                NOT NULL,   /*起点日期*/
  C_DEPART    NUMBER(18)          NOT NULL,   /*部门*/
  C_OFFICE    VARCHAR2(40 BYTE)   NOT NULL,   /*考勤组名称*/
  C_CHECKDATE DATE                NOT NULL,   /*修改日期*/
  C_CHECKBY   NUMBER(18)          NOT NULL,   /*录入人*/
  C_COMMENT   VARCHAR2(255 BYTE)  NULL
) LOGGING NOCACHE NOPARALLEL MONITORING;
--关键字
ALTER TABLE T_HRCHK_PLAN ADD (CONSTRAINT PK_HRCHK_PLAN PRIMARY KEY (C_BELONG, C_NO));
--外键
ALTER TABLE T_HRCHK_PLAN ADD (CONSTRAINT FK_HRCHKPLAN_DEPT FOREIGN KEY (C_BELONG, C_DEPART) REFERENCES T_DEPARTMENT (C_BELONG,C_DEPARTMENTID));
ALTER TABLE T_HRCHK_PLAN ADD (CONSTRAINT FK_HRCHKPLAN_CHECK FOREIGN KEY (C_BELONG, C_CHECKBY) REFERENCES T_PERSONAL (C_BELONG,C_PERSONALID));
