SET ECHO OFF
SET VERIFY OFF
SET HEADING OFF

--出勤计划表明细
EXEC SP_DROPTABLE('T_HRCHK_PLANDT');
CREATE TABLE T_HRCHK_PLANDT
(
  C_BELONG    NUMBER(18)                          NOT NULL,
  C_HDNO      VARCHAR2(30 BYTE)                   NOT NULL, /*凭证号*/
  C_NO        NUMBER(3)                           NOT NULL, /*序号*/
  C_PERSON    NUMBER(18)                          NOT NULL, /*人*/
  C_DATE      DATE                                NOT NULL, /*日期*/
  C_HLDAY     NUMBER(18)                          NULL,     /*休假计划*/
  C_WORK      NUMBER(18)                          NULL,     /*出勤计划*/
  C_EXTR      NUMBER(18)                          NULL      /*加班计划*/  
) LOGGING NOCACHE NOPARALLEL NOMONITORING;
--关键字
ALTER TABLE T_HRCHK_PLANDT ADD (CONSTRAINT PK_HRCHK_PLANDT PRIMARY KEY (C_BELONG, C_HDNO, C_NO));
--唯一性索引
CREATE UNIQUE INDEX IDX_HRCHK_PLANDT ON T_HRCHK_PLANDT (C_BELONG, C_PERSON, C_DATE) LOGGING NOPARALLEL;
--外键
ALTER TABLE T_HRCHK_PLANDT ADD (CONSTRAINT FK_HRCHK_PLANDT_HDNO FOREIGN KEY (C_BELONG, C_HDNO) REFERENCES T_HRCHK_PLAN (C_BELONG,C_NO));
ALTER TABLE T_HRCHK_PLANDT ADD (CONSTRAINT FK_HRCHK_PLANDT_PSN FOREIGN KEY (C_BELONG, C_PERSON) REFERENCES T_PERSONAL (C_BELONG,C_PERSONALID));
ALTER TABLE T_HRCHK_PLANDT ADD (CONSTRAINT FK_HRCHK_PLANDT_HLDAY FOREIGN KEY (C_BELONG, C_HLDAY) REFERENCES T_HRCHK_HLDAY (C_BELONG,C_ID));
ALTER TABLE T_HRCHK_PLANDT ADD (CONSTRAINT FK_HRCHK_PLANDT_WORK FOREIGN KEY (C_BELONG, C_WORK) REFERENCES T_HRCHK_WORK (C_BELONG,C_ID));
ALTER TABLE T_HRCHK_PLANDT ADD (CONSTRAINT FK_HRCHK_PLANDT_EXTR FOREIGN KEY (C_BELONG, C_EXTR) REFERENCES T_HRCHK_EXTR (C_BELONG,C_ID));
