SET ECHO OFF
SET VERIFY OFF
SET HEADING OFF

--实际出勤表明细
EXEC SP_DROPTABLE('T_HRCHK_FACTDT');
CREATE TABLE T_HRCHK_FACTDT
(
  C_BELONG  NUMBER(18)                          NOT NULL,
  C_HDNO    VARCHAR2(30 BYTE)                   NOT NULL, /*凭证号*/
  c_NO      NUMBER(3)                           NOT NULL, /*序号*/
  C_PERSON  NUMBER(18)                          NOT NULL, /*人*/
  C_DATE    DATE                                NOT NULL, /*日期*/
  C_HLDAY   NUMBER(18)                          NULL,     /*休假项目*/
  C_WORK    NUMBER(18)                          NULL,     /*出勤项目*/
  C_EXTR    NUMBER(18)                          NULL,     /*加班项目*/  
  C_DISP    NUMBER(18)                          NULL      /*违纪项目*/
) LOGGING NOCACHE NOPARALLEL NOMONITORING;
--关键字
ALTER TABLE T_HRCHK_FACTDT ADD (CONSTRAINT PK_HRCHK_FACTDT PRIMARY KEY (C_BELONG, C_HDNO, C_NO));
--唯一性索引
CREATE UNIQUE INDEX IDX_HRCHK_FACTDT ON T_HRCHK_FACTDT (C_BELONG, C_PERSON, C_DATE) LOGGING NOPARALLEL;
--外键
ALTER TABLE T_HRCHK_FACTDT ADD (CONSTRAINT FK_HRCHK_FACTDT_HDNO FOREIGN KEY (C_BELONG, C_HDNO) REFERENCES T_HRCHK_FACT (C_BELONG,C_NO));
ALTER TABLE T_HRCHK_FACTDT ADD (CONSTRAINT FK_HRCHK_FACTDT_PSN FOREIGN KEY (C_BELONG, C_PERSON) REFERENCES T_PERSONAL (C_BELONG,C_PERSONALID));
ALTER TABLE T_HRCHK_FACTDT ADD (CONSTRAINT FK_HRCHK_FACTDT_HLDAY FOREIGN KEY (C_BELONG, C_HLDAY) REFERENCES T_HRCHK_HLDAY (C_BELONG,C_ID));
ALTER TABLE T_HRCHK_FACTDT ADD (CONSTRAINT FK_HRCHK_FACTDT_WORK FOREIGN KEY (C_BELONG, C_WORK) REFERENCES T_HRCHK_WORK (C_BELONG,C_ID));
ALTER TABLE T_HRCHK_FACTDT ADD (CONSTRAINT FK_HRCHK_FACTDT_EXTR FOREIGN KEY (C_BELONG, C_EXTR) REFERENCES T_HRCHK_EXTR (C_BELONG,C_ID));
ALTER TABLE T_HRCHK_FACTDT ADD (CONSTRAINT FK_HRCHK_FACTDT_DISP FOREIGN KEY (C_BELONG, C_DISP) REFERENCES T_HRCHK_DISP (C_BELONG,C_ID));
