SET ECHO OFF
SET VERIFY OFF
SET HEADING OFF

/*
INSERT INTO T_PSN_STATUS
   (C_BELONG, C_PERSON, C_UPGRADE_REASON, C_TYPE, C_POSITION, 
    C_REGBELONG, C_PARTY, C_GRADE, C_SCHOOLHISTORY, C_ONDATE, 
    C_DOWNDATE, C_UPGRADER)
 Values
   (2, 8238, NULL, '合同', '1', 
    NULL, '党员', NULL, '本科', TO_DATE('05/20/2009 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), 
    TO_DATE('12/31/9999 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), 11);
COMMIT;
*/

INSERT INTO T_DEPARTTERM
   (C_BELONG, C_DEPART, C_NAME, C_MANDUTY, C_LEADER, 
    C_COMMENT)
 Values
   (2, 4, '财务部', NULL, NULL, 
    NULL);
COMMIT;

INSERT INTO T_PSN_PEOPLE
   (C_BELONG, C_NAME, C_NO, C_ACTIVE)
 Values
   (2, '汉族', 0, 1);
INSERT INTO T_PSN_PEOPLE
   (C_BELONG, C_NAME, C_NO, C_ACTIVE)
 Values
   (2, '满族', 0, 1);
INSERT INTO T_PSN_PEOPLE
   (C_BELONG, C_NAME, C_NO, C_ACTIVE)
 Values
   (2, '回族', 0, 1);
INSERT INTO T_PSN_PEOPLE
   (C_BELONG, C_NAME, C_NO, C_ACTIVE)
 Values
   (2, '维吾尔族', 0, 1);
INSERT INTO T_PSN_PEOPLE
   (C_BELONG, C_NAME, C_NO, C_ACTIVE)
 Values
   (2, '藏族', 0, 1);
COMMIT;

INSERT INTO T_PSN_NPLACE
   (C_BELONG, C_NAME, C_NO, C_ACTIVE)
 Values
   (2, '江苏省苏州市', 0, 1);
INSERT INTO T_PSN_NPLACE
   (C_BELONG, C_NAME, C_NO, C_ACTIVE)
 Values
   (2, '上海市徐汇区', 0, 1);
COMMIT;

INSERT INTO T_PSN_MSTATE
   (C_BELONG, C_NAME, C_NO, C_ACTIVE)
 Values
   (2, '未婚', 0, 1);
INSERT INTO T_PSN_MSTATE
   (C_BELONG, C_NAME, C_NO, C_ACTIVE)
 Values
   (2, '已婚', 0, 1);
INSERT INTO T_PSN_MSTATE
   (C_BELONG, C_NAME, C_NO, C_ACTIVE)
 Values
   (2, '离异', 0, 1);
INSERT INTO T_PSN_MSTATE
   (C_BELONG, C_NAME, C_NO, C_ACTIVE)
 Values
   (2, '单身', 0, 1);
COMMIT;

INSERT INTO T_PSN_TYPE
   (C_BELONG, C_NAME, C_NO, C_ACTIVE)
 Values
   (2, '合同', 0, 1);
INSERT INTO T_PSN_TYPE
   (C_BELONG, C_NAME, C_NO, C_ACTIVE)
 Values
   (2, '镇保', 0, 1);
INSERT INTO T_PSN_TYPE
   (C_BELONG, C_NAME, C_NO, C_ACTIVE)
 Values
   (2, '返聘', 0, 1);
INSERT INTO T_PSN_TYPE
   (C_BELONG, C_NAME, C_NO, C_ACTIVE)
 Values
   (2, '病假', 0, 1);
INSERT INTO T_PSN_TYPE
   (C_BELONG, C_NAME, C_NO, C_ACTIVE)
 Values
   (2, '实习', 0, 1);
INSERT INTO T_PSN_TYPE
   (C_BELONG, C_NAME, C_NO, C_ACTIVE)
 Values
   (2, '试用', 0, 1);
INSERT INTO T_PSN_TYPE
   (C_BELONG, C_NAME, C_NO, C_ACTIVE)
 Values
   (2, '临时工', 0, 1);
INSERT INTO T_PSN_TYPE
   (C_BELONG, C_NAME, C_NO, C_ACTIVE)
 Values
   (2, '闲置临时工', 0, 1);
INSERT INTO T_PSN_TYPE
   (C_BELONG, C_NAME, C_NO, C_ACTIVE)
 Values
   (2, '辞职', 0, 1);
INSERT INTO T_PSN_TYPE
   (C_BELONG, C_NAME, C_NO, C_ACTIVE)
 Values
   (2, 'N/A', 0, 1);
INSERT INTO T_PSN_TYPE
   (C_BELONG, C_NAME, C_NO, C_ACTIVE)
 Values
   (4, 'N/A', 0, 1);
COMMIT;

INSERT INTO T_PSN_REGBELONG
   (C_BELONG, C_NAME, C_NO, C_ACTIVE)
 Values
   (2, '浦强', 0, 1);
INSERT INTO T_PSN_REGBELONG
   (C_BELONG, C_NAME, C_NO, C_ACTIVE)
 Values
   (2, '公交', 0, 1);
INSERT INTO T_PSN_REGBELONG
   (C_BELONG, C_NAME, C_NO, C_ACTIVE)
 Values
   (2, '旅汽', 0, 1);
COMMIT;

INSERT INTO T_PSN_PARTY
   (C_BELONG, C_NAME, C_NO, C_ACTIVE)
 Values
   (2, '党员', 0, 1);
INSERT INTO T_PSN_PARTY
   (C_BELONG, C_NAME, C_NO, C_ACTIVE)
 Values
   (2, '团员', 0, 1);
INSERT INTO T_PSN_PARTY
   (C_BELONG, C_NAME, C_NO, C_ACTIVE)
 Values
   (2, '群众', 0, 1);
COMMIT;

INSERT INTO T_PSN_SCHOOLING
   (C_BELONG, C_NAME, C_NO, C_ACTIVE)
 Values
   (2, '小学', 0, 1);
INSERT INTO T_PSN_SCHOOLING
   (C_BELONG, C_NAME, C_NO, C_ACTIVE)
 Values
   (2, '初中', 0, 1);
INSERT INTO T_PSN_SCHOOLING
   (C_BELONG, C_NAME, C_NO, C_ACTIVE)
 Values
   (2, '高中', 0, 1);
INSERT INTO T_PSN_SCHOOLING
   (C_BELONG, C_NAME, C_NO, C_ACTIVE)
 Values
   (2, '中专', 0, 1);
INSERT INTO T_PSN_SCHOOLING
   (C_BELONG, C_NAME, C_NO, C_ACTIVE)
 Values
   (2, '大专', 0, 1);
INSERT INTO T_PSN_SCHOOLING
   (C_BELONG, C_NAME, C_NO, C_ACTIVE)
 Values
   (2, '本科', 0, 1);
INSERT INTO T_PSN_SCHOOLING
   (C_BELONG, C_NAME, C_NO, C_ACTIVE)
 Values
   (2, '硕士', 0, 1);
INSERT INTO T_PSN_SCHOOLING
   (C_BELONG, C_NAME, C_NO, C_ACTIVE)
 Values
   (2, '博士', 0, 1);
INSERT INTO T_PSN_SCHOOLING
   (C_BELONG, C_NAME, C_NO, C_ACTIVE)
 Values
   (4, '大专', 0, 1);
INSERT INTO T_PSN_SCHOOLING
   (C_BELONG, C_NAME, C_NO, C_ACTIVE)
 Values
   (4, '本科', 0, 1);
INSERT INTO T_PSN_SCHOOLING
   (C_BELONG, C_NAME, C_NO, C_ACTIVE)
 Values
   (4, '研究生', 0, 1);
INSERT INTO T_PSN_SCHOOLING
   (C_BELONG, C_NAME, C_NO, C_ACTIVE)
 Values
   (4, '博士', 0, 1);
COMMIT;

INSERT INTO T_PSN_SPEC
   (C_BELONG, C_NAME, C_NO, C_ACTIVE)
 Values
   (2, '电工', 0, 1);
INSERT INTO T_PSN_SPEC
   (C_BELONG, C_NAME, C_NO, C_ACTIVE)
 Values
   (2, '机工', 0, 1);
INSERT INTO T_PSN_SPEC
   (C_BELONG, C_NAME, C_NO, C_ACTIVE)
 Values
   (4, '会计员', 0, 1);
INSERT INTO T_PSN_SPEC
   (C_BELONG, C_NAME, C_NO, C_ACTIVE)
 Values
   (4, '汽车运用工程', 0, 1);
COMMIT;

INSERT INTO T_HRSAL_ITEM
   (C_BELONG, C_ID, C_NO, C_NAME, C_ONDATE, 
    C_DOWNDATE, C_ACCOUNT_DEBIT, C_ACCOUNT_CREDIT, C_FLAG, C_TYPE)
 Values
   (2, 1, 'JB', '加班费', TO_DATE('01/01/1900 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), 
    TO_DATE('12/31/9999 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), NULL, NULL, 1, 'WG');
INSERT INTO T_HRSAL_ITEM
   (C_BELONG, C_ID, C_NO, C_NAME, C_ONDATE, 
    C_DOWNDATE, C_ACCOUNT_DEBIT, C_ACCOUNT_CREDIT, C_FLAG, C_TYPE)
 Values
   (2, 2, 'GZ', '工资', TO_DATE('01/01/1900 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), 
    TO_DATE('12/31/9999 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), NULL, NULL, 1, 'WG');
INSERT INTO T_HRSAL_ITEM
   (C_BELONG, C_ID, C_NO, C_NAME, C_ONDATE, 
    C_DOWNDATE, C_ACCOUNT_DEBIT, C_ACCOUNT_CREDIT, C_FLAG, C_TYPE)
 Values
   (2, 3, 'CB', '承包
', TO_DATE('01/01/1900 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), 
    TO_DATE('12/31/9999 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), NULL, NULL, 1, 'WG');
INSERT INTO T_HRSAL_ITEM
   (C_BELONG, C_ID, C_NO, C_NAME, C_ONDATE, 
    C_DOWNDATE, C_ACCOUNT_DEBIT, C_ACCOUNT_CREDIT, C_FLAG, C_TYPE)
 Values
   (2, 4, 'FT', '副贴', TO_DATE('01/01/1900 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), 
    TO_DATE('12/31/9999 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), NULL, NULL, 1, 'WG');
INSERT INTO T_HRSAL_ITEM
   (C_BELONG, C_ID, C_NO, C_NAME, C_ONDATE, 
    C_DOWNDATE, C_ACCOUNT_DEBIT, C_ACCOUNT_CREDIT, C_FLAG, C_TYPE)
 Values
   (2, 5, 'GJJ', '公积金
', TO_DATE('01/01/1900 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), 
    TO_DATE('12/31/9999 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), NULL, NULL, -1, 'SG');
INSERT INTO T_HRSAL_ITEM
   (C_BELONG, C_ID, C_NO, C_NAME, C_ONDATE, 
    C_DOWNDATE, C_ACCOUNT_DEBIT, C_ACCOUNT_CREDIT, C_FLAG, C_TYPE)
 Values
   (2, 6, 'DK', '代扣', TO_DATE('01/01/1900 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), 
    TO_DATE('12/31/9999 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), NULL, NULL, -1, 'DK');
COMMIT;

INSERT INTO T_HRSAL_DEPTPSN
   (C_BELONG, C_DEPART, C_PERSON, C_BANK, C_BANKCARD, 
    C_COMMENT)
 Values
   (2, 2, 8, '上海浦东发展银行陆家嘴分理处', '123456789000', 
    'TEST');
COMMIT;

INSERT INTO T_HRSAL_FIXONLINE
   (C_ID, C_BELONG, C_DEPART, C_PERSON, C_ITEM, 
    C_ONDATE, C_DOWNDATE, C_AMOUNT, C_COMMENT)
 Values
   (1, 2, 2, 8, 1, 
    TO_DATE('05/01/2008 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), TO_DATE('05/31/2008 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), 80, NULL);
COMMIT;

INSERT INTO T_HRSAL_TEMPLATE
   (C_ID, C_BELONG, C_DEPART, C_ITEM, C_AMOUNT, 
    C_COMMENT)
 Values
   (1, 2, 5, 1, 80, 
    NULL);
COMMIT;

INSERT INTO T_HRCHK_FACTHD
   (C_BELONG, C_NO, C_DEPART, C_OFFICE, C_CHECKBY, 
    C_COMMENT)
 Values
   (2, '1', 2, NULL, 1, 
    NULL);
COMMIT;