SET ECHO OFF
SET VERIFY OFF
SET HEADING OFF

EXEC SP_DROPTABLE('T_HRCHK_ITEM');

--考勤项目表
CREATE TABLE T_HRCHK_ITEM
(
  C_BELONG    NUMBER(18)                        NOT NULL,
  C_ID        NUMBER(18)                        NOT NULL,
  C_NO        VARCHAR2(16 BYTE)                 NOT NULL, /*项目标号*/
  C_NAME      VARCHAR2(30 BYTE)                 NOT NULL, /*项目名称*/
  C_ONDATE    DATE                              NOT NULL, /*启用日期*/
  C_DOWNDATE  DATE                              NOT NULL, /*停用日期-包含端点*/
  C_COMMENT   VARCHAR2(255 BYTE)                    NULL
) LOGGING NOCACHE NOPARALLEL MONITORING;

CREATE INDEX IDX_HRCHK_ITEM ON T_HRCHK_ITEM (C_BELONG) LOGGING NOPARALLEL;
CREATE UNIQUE INDEX IDX_HRCHK_ITEMID ON T_HRCHK_ITEM (C_ID) LOGGING NOPARALLEL;
CREATE UNIQUE INDEX IDX_HRCHK_ITEMNO ON T_HRCHK_ITEM (C_BELONG, C_NO) LOGGING NOPARALLEL;
ALTER TABLE T_HRCHK_ITEM ADD (CONSTRAINT PK_HRCHK_ITEM PRIMARY KEY (C_BELONG, C_ID));
ALTER TABLE T_HRCHK_ITEM ADD (CONSTRAINT FK_HRCHK_ITEM FOREIGN KEY (C_BELONG) REFERENCES T_BRANCH (C_BRANCHID));

EXEC SP_DROPSEQ('SEQ_HRCHK_ITEM');
CREATE SEQUENCE SEQ_HRCHK_ITEM START WITH 1 MAXVALUE 999999999999999999999999999 MINVALUE 1 NOCYCLE NOCACHE NOORDER;

CREATE OR REPLACE TRIGGER TRG_HRCHK_ITEMID
BEFORE INSERT ON T_HRCHK_ITEM
FOR EACH ROW
DECLARE NEXT_ID NUMBER;
BEGIN
  SELECT SEQ_HRCHK_ITEM.NEXTVAL INTO NEXT_ID FROM T_SEQFRO;
  :NEW.C_ID := NEXT_ID;
END;
/