SET ECHO OFF
SET VERIFY OFF
SET HEADING OFF

EXEC SP_DROPTABLE('T_HRCHK_FACTHD');
--考勤表凭证头
CREATE TABLE T_HRCHK_FACTHD
(
  C_BELONG   NUMBER(18)         NOT NULL,
  C_NO       VARCHAR2(30 BYTE)  NOT NULL, /*凭证号*/
  C_DATE     DATE               NOT NULL, /*日期*/
  C_DEPART   NUMBER(18)         NOT NULL, /*部门*/
  C_OFFICE   VARCHAR2(40 BYTE)      NULL, /*车队*/
  C_CHECKBY  NUMBER(18)         NOT NULL, /*录入人*/
  C_COMMENT  VARCHAR2(255 BYTE)     NULL
) LOGGING NOCACHE NOPARALLEL MONITORING;

CREATE UNIQUE INDEX IDX_HRCHK_FACTHDNO ON T_HRCHK_FACTHD (C_NO) LOGGING NOPARALLEL;
CREATE INDEX IDX_HRCHK_FACTHD_TERM ON T_HRCHK_FACTHD (C_BELONG, C_DEPART, C_OFFICE) LOGGING NOPARALLEL;
ALTER TABLE T_HRCHK_FACTHD ADD (CONSTRAINT PK_HRCHK_FACTHD PRIMARY KEY (C_BELONG, C_NO));
ALTER TABLE T_HRCHK_FACTHD ADD (CONSTRAINT FK_HRCHK_FACTHD_DEPT FOREIGN KEY (C_BELONG, C_DEPART) REFERENCES T_DEPARTMENT (C_BELONG,C_DEPARTMENTID));
-- 部门处室表不维护历史，可以直接删除，此处不加外键可以记录旧处室的考勤记录
-- ALTER TABLE T_HRCHK_FACTHD ADD (CONSTRAINT FK_HRCHK_FACTHD_TERM FOREIGN KEY (C_BELONG, C_DEPART, C_OFFICE) REFERENCES T_DEPARTTERM (C_BELONG,C_DEPART,C_NAME));
