SET ECHO OFF
SET VERIFY OFF
SET HEADING OFF

EXEC SP_DROPTABLE('T_HRCHK_FACTDT');
--考勤表凭证明细
CREATE TABLE T_HRCHK_FACTDT
(
  C_BELONG  NUMBER(18)                          NOT NULL,
  C_HDNO    VARCHAR2(30 BYTE)                   NOT NULL, /*凭证号*/
  C_NO      NUMBER(3)                           NOT NULL, /*序号*/
  C_ITEM    NUMBER(18)                          NOT NULL, /*项目*/
  C_PERSON  NUMBER(18)                          NOT NULL, /*人*/
  C_FROM    DATE                                NOT NULL, /*起点时刻*/
  C_END     DATE                                NOT NULL  /*终点时刻*/
) LOGGING NOCACHE NOPARALLEL NOMONITORING;

CREATE INDEX IDX_HRCHK_FACTDT_HDNO ON T_HRCHK_FACTDT (C_BELONG, C_HDNO) LOGGING NOPARALLEL;
CREATE INDEX IDX_HRCHK_FACTDT_PSN ON T_HRCHK_FACTDT (C_BELONG, C_HDNO, C_PERSON) LOGGING NOPARALLEL;
CREATE INDEX IDX_HRCHK_FACTDT_ITEM ON T_HRCHK_FACTDT (C_BELONG, C_HDNO, C_ITEM) LOGGING NOPARALLEL;
ALTER TABLE T_HRCHK_FACTDT ADD (CONSTRAINT PK_HRCHK_FACTDT PRIMARY KEY (C_BELONG, C_HDNO, C_NO, C_ITEM));
--Check 单人时间考勤表重复错误，提示信息用户要指出C_HDNO和C_NO,C_ITEM便于用户查到单人和时点的已有考勤状态。
ALTER TABLE T_HRCHK_FACTDT ADD (CONSTRAINT FK_HRCHK_FACTDT_HDNO FOREIGN KEY (C_BELONG, C_HDNO) REFERENCES T_HRCHK_FACTHD (C_BELONG,C_NO));
ALTER TABLE T_HRCHK_FACTDT ADD (CONSTRAINT FK_HRCHK_FACTDT_ITEM FOREIGN KEY (C_BELONG, C_ITEM) REFERENCES T_HRCHK_ITEM (C_BELONG,C_ID));
ALTER TABLE T_HRCHK_FACTDT ADD (CONSTRAINT FK_HRCHK_FACTDT_PSN FOREIGN KEY (C_BELONG, C_PERSON) REFERENCES T_PERSONAL (C_BELONG,C_PERSONALID));