--本脚本只用于 HR模块
--164部门处室表
CREATE TABLE T_DEPARTTERM
(
  C_BELONG   NUMBER(18)                         NOT NULL,
  C_DEPART   NUMBER(18)                         NOT NULL,
  C_NAME     VARCHAR2(40 BYTE)                  NOT NULL,
  C_MANDUTY  VARCHAR2(400 BYTE)                     NULL,
  C_LEADER   NUMBER(18)                             NULL,
  C_COMMENT  VARCHAR2(255 BYTE)                     NULL,
  CONSTRAINT PK_DEPARTTERM PRIMARY KEY (C_BELONG, C_DEPART, C_NAME),
  CONSTRAINT FK_DEPARTTERM FOREIGN KEY (C_BELONG, C_DEPART) REFERENCES T_DEPARTMENT
)
LOGGING 
NOCACHE
NOPARALLEL
MONITORING;

insert into T_DEPARTTERM
  (C_BELONG, c_Depart, c_Name)
  (select distinct C_BELONG, c_Depart, nvl(c_Office, 'N/A') from T_PERSONAL);
commit;
--起用人员表限制
ALTER TABLE PEADMIN.T_PERSONAL ADD (
  CONSTRAINT FK_PERSONAL_DEPARTTERM 
 FOREIGN KEY (C_BELONG,C_DEPART,C_OFFICE) 
 REFERENCES PEADMIN.T_DEPARTTERM (C_BELONG,C_DEPART,C_NAME));


ALTER TABLE PEADMIN.t_psn_online ADD (
  CONSTRAINT FK_psnon_deptterm FOREIGN KEY (c_Belong,c_Depart,c_Office) REFERENCES PEADMIN.T_DEPARTTERM (C_BELONG, C_DEPART, C_NAME)
);


--
CREATE TABLE T_PSN_PEOPLE
(
  C_BELONG  NUMBER(18)                              not NULL,
  C_NAME    VARCHAR2(20 BYTE)                       not NULL,
  C_NO      NUMBER(18,2)                        DEFAULT 0                         not NULL,
  C_ACTIVE  NUMBER(1)                           DEFAULT 1                         not NULL,
 CONSTRAINT PK_PSN_PEOPLE PRIMARY KEY (C_BELONG, C_NAME),
 CONSTRAINT FK_PSN_PEOPLE FOREIGN KEY (C_BELONG) REFERENCES T_BRANCH 
)
LOGGING 
NOCACHE
NOPARALLEL
NOMONITORING;
ALTER TABLE PEADMIN.T_PERSONAL ADD (
  CONSTRAINT FK_PERSONAL_PEOPLE 
 FOREIGN KEY (C_BELONG,C_PEOPLE) 
 REFERENCES PEADMIN.T_PSN_PEOPLE (C_BELONG,C_NAME));
-----------------------------------------------------


CREATE TABLE T_PSN_NPLACE
(
  C_BELONG  NUMBER(18)                              not NULL,
  C_NAME    VARCHAR2(20 BYTE)                       not NULL,
  C_NO      NUMBER(18,2)                        DEFAULT 0                         not NULL,
  C_ACTIVE  NUMBER(1)                           DEFAULT 1                         not NULL,
  CONSTRAINT PK_PSN_NPLACE PRIMARY KEY (C_BELONG, C_NAME),
  CONSTRAINT FK_PSN_NPLACE FOREIGN KEY (C_BELONG) REFERENCES T_BRANCH
)
LOGGING 
NOCACHE
NOPARALLEL
NOMONITORING;

ALTER TABLE PEADMIN.T_PERSONAL ADD (
  CONSTRAINT FK_PERSONAL_NPLACE 
 FOREIGN KEY (C_BELONG,C_NATIVEPLACE) 
 REFERENCES PEADMIN.T_PSN_NPLACE (C_BELONG,C_NAME));
-----------------------------------------------------

--164婚姻状态表
CREATE TABLE T_PSN_MSTATE
(
  C_BELONG  NUMBER(18)                              not NULL,
  C_NAME    VARCHAR2(4 BYTE)                        not NULL,
  C_NO      NUMBER(18,2)                        DEFAULT 0                         not NULL,
  C_ACTIVE  NUMBER(1)                           DEFAULT 1                         not NULL,
  CONSTRAINT PK_PSN_MSTATE PRIMARY KEY (C_BELONG, C_NAME),
  CONSTRAINT FK_PSN_MSTATE FOREIGN KEY (C_BELONG) REFERENCES T_BRANCH
)
LOGGING 
NOCACHE
NOPARALLEL
NOMONITORING;

ALTER TABLE PEADMIN.T_PERSONAL ADD (
  CONSTRAINT FK_PERSONAL_MSTATE 
 FOREIGN KEY (C_BELONG,C_MARRYSTATE) 
 REFERENCES PEADMIN.T_PSN_MSTATE (C_BELONG,C_NAME));


--164所属法人单位表
CREATE TABLE T_PSN_REGBELONG
(
  C_BELONG  NUMBER(18)                              not NULL,
  C_NAME    VARCHAR2(20 BYTE)                       not NULL,
  C_NO      NUMBER(18,2)                        DEFAULT 0                         not NULL,
  C_ACTIVE  NUMBER(1)                           DEFAULT 1                         not NULL,
  CONSTRAINT PK_PSN_REGBELONG PRIMARY KEY (C_BELONG, C_NAME),
  CONSTRAINT FK_PSN_REGBELONG FOREIGN KEY (C_BELONG) REFERENCES T_BRANCH
)
LOGGING 
NOCACHE
NOPARALLEL
NOMONITORING;

ALTER TABLE PEADMIN.T_PERSONAL ADD (
  CONSTRAINT FK_PERSONAL_REGBELONG 
 FOREIGN KEY (C_BELONG,C_REGBELONG) 
 REFERENCES PEADMIN.T_PSN_REGBELONG (C_BELONG,C_NAME));
-----------------------------------------------------
--164政治面貌表
CREATE TABLE T_PSN_PARTY
(
  C_BELONG  NUMBER(18)                              not NULL,
  C_NAME    VARCHAR2(12 BYTE)                       not NULL,
  C_NO      NUMBER(18,2)                        DEFAULT 0                         not NULL,
  C_ACTIVE  NUMBER(1)                           DEFAULT 1                         not NULL,
  CONSTRAINT PK_PSN_PARTY PRIMARY KEY (C_BELONG, C_NAME),
  CONSTRAINT FK_PSN_PARTY FOREIGN KEY (C_BELONG) REFERENCES T_BRANCH
)
LOGGING 
NOCACHE
NOPARALLEL
NOMONITORING;

ALTER TABLE PEADMIN.T_PERSONAL ADD (
  CONSTRAINT FK_PERSONAL_PARTY 
 FOREIGN KEY (C_BELONG,C_PARTY) 
 REFERENCES PEADMIN.T_PSN_PARTY (C_BELONG,C_NAME));
-----------------------------------------------------
--164职称表
CREATE TABLE T_PSN_GRADE
(
  C_BELONG  NUMBER(18)                              not NULL,
  C_NAME    VARCHAR2(40 BYTE)                       not NULL,
  C_NO      NUMBER(18,2)                        DEFAULT 0                         not NULL,
  C_ACTIVE  NUMBER(1)                           DEFAULT 1                         not NULL,
  CONSTRAINT PK_PSN_GRADE PRIMARY KEY (C_BELONG, C_NAME),
  CONSTRAINT FK_PSN_GRADE FOREIGN KEY (C_BELONG) REFERENCES T_BRANCH
)
LOGGING 
NOCACHE
NOPARALLEL
NOMONITORING;

ALTER TABLE PEADMIN.T_PERSONAL ADD (
  CONSTRAINT FK_PERSONAL_GRADE 
 FOREIGN KEY (C_BELONG,C_GRADE) 
 REFERENCES PEADMIN.T_PSN_GRADE (C_BELONG,C_NAME));
-----------------------------------------------------
--164学历表
CREATE TABLE T_PSN_SCHOOLING
(
  C_BELONG  NUMBER(18)                              not NULL,
  C_NAME    VARCHAR2(60 BYTE)                       not NULL,
  C_NO      NUMBER(18,2)                        DEFAULT 0                         not NULL,
  C_ACTIVE  NUMBER(1)                           DEFAULT 1                         not NULL,
  CONSTRAINT PK_PSN_SCHOOLING PRIMARY KEY (C_BELONG, C_NAME),
  CONSTRAINT FK_PSN_SCHOOLING FOREIGN KEY (C_BELONG) REFERENCES T_BRANCH
)
LOGGING 
NOCACHE
NOPARALLEL
NOMONITORING;


insert into PEADMIN.T_PSN_SCHOOLING (C_BELONG,C_NAME)
select distinct PEADMIN.T_PERSONAL.C_BELONG, nvl(PEADMIN.T_PERSONAL.C_SCHOOLHISTORY, 'N/A') from PEADMIN.T_PERSONAL;
commit;

ALTER TABLE PEADMIN.T_PERSONAL ADD (
  CONSTRAINT FK_PERSONAL_SCHOOLING 
 FOREIGN KEY (C_BELONG,C_SCHOOLHISTORY) 
 REFERENCES PEADMIN.T_PSN_SCHOOLING (C_BELONG,C_NAME));
-----------------------------------------------------
--164专业表
CREATE TABLE T_PSN_SPEC
(
  C_BELONG  NUMBER(18)                              not NULL,
  C_NAME    VARCHAR2(60 BYTE)                       not NULL,
  C_NO      NUMBER(18,2)                        DEFAULT 0                         not NULL,
  C_ACTIVE  NUMBER(1)                           DEFAULT 1                         not NULL,
  CONSTRAINT PK_PSN_SPEC PRIMARY KEY (C_BELONG, C_NAME),
  CONSTRAINT FK_PSN_SPEC FOREIGN KEY (C_BELONG) REFERENCES T_BRANCH 
)
LOGGING 
NOCACHE
NOPARALLEL
NOMONITORING;


insert into PEADMIN.T_PSN_SPEC (C_BELONG,C_NAME)
select distinct PEADMIN.T_PERSONAL.C_BELONG, nvl(PEADMIN.T_PERSONAL.C_SPECIFICATION, 'N/A') from PEADMIN.T_PERSONAL;
commit;

ALTER TABLE PEADMIN.T_PERSONAL ADD (
  CONSTRAINT FK_PERSONAL_SPEC 
 FOREIGN KEY (C_BELONG,C_SPECIFICATION) 
 REFERENCES PEADMIN.T_PSN_SPEC (C_BELONG,C_NAME));
-----------------------------------------------------
--164学位表
CREATE TABLE T_PSN_DEGREE
(
  C_BELONG  NUMBER(18)                              not NULL,
  C_NAME    VARCHAR2(60 BYTE)                       not NULL,
  C_NO      NUMBER(18,2)                        DEFAULT 0                         not NULL,
  C_ACTIVE  NUMBER(1)                           DEFAULT 1                         not NULL,
  CONSTRAINT PK_PSN_DEGREE PRIMARY KEY (C_BELONG, C_NAME),
  CONSTRAINT FK_PSN_DEGREE FOREIGN KEY (C_BELONG) REFERENCES T_BRANCH
)
LOGGING 
NOCACHE
NOPARALLEL
NOMONITORING;

ALTER TABLE PEADMIN.T_PERSONAL ADD (
  CONSTRAINT FK_PERSONAL_DEGREE 
 FOREIGN KEY (C_BELONG,C_DEGREE) 
 REFERENCES PEADMIN.T_PSN_DEGREE (C_BELONG,C_NAME));
-----------------------------------------------------
--164毕业院校表
CREATE TABLE T_PSN_GRADUATE
(
  C_BELONG  NUMBER(18)                              not NULL,
  C_NAME    VARCHAR2(20 BYTE)                       not NULL,
  C_NO      NUMBER(18,1)                        DEFAULT 0                         not NULL,
  C_ACTIVE  NUMBER(1)                           DEFAULT 1                         not NULL,
  CONSTRAINT PK_PSN_GRADUATE PRIMARY KEY (C_BELONG, C_NAME),
  CONSTRAINT FK_PSN_GRADUATE FOREIGN KEY (C_BELONG) REFERENCES T_BRANCH
)
LOGGING 
NOCACHE
NOPARALLEL
NOMONITORING;

ALTER TABLE PEADMIN.T_PERSONAL ADD (
  CONSTRAINT FK_PERSONAL_GRADUATE 
 FOREIGN KEY (C_BELONG,C_GRADUATE) 
 REFERENCES PEADMIN.T_PSN_GRADUATE (C_BELONG,C_NAME));