  ALTER TABLE PEADMIN.T_PERSONAL drop CONSTRAINT FK_PERSONAL_DEPARTTERM;
  ALTER TABLE PEADMIN.T_PSN_ONLINE drop CONSTRAINT FK_PSNON_DEPTTERM;
  ALTER TABLE T_HRCHK_DEPTTERM_PSN drop CONSTRAINT FK_HRCHK_DEPTTERM_TERM;
  drop TABLE T_DEPARTTERM;
  ALTER TABLE PEADMIN.T_PERSONAL DROP CONSTRAINT FK_PERSONAL_PEOPLE;
  DROP TABLE T_PSN_PEOPLE;
  ALTER TABLE PEADMIN.T_PERSONAL DROP CONSTRAINT FK_PERSONAL_NPLACE;
  DROP TABLE T_PSN_NPLACE;
  ALTER TABLE PEADMIN.T_PERSONAL DROP CONSTRAINT FK_PERSONAL_MSTATE ;
  DROP TABLE T_PSN_MSTATE;

  --
  ALTER TABLE PEADMIN.T_PERSONAL DROP  CONSTRAINT FK_PERSONAL_REGBELONG;
  DROP TABLE T_PSN_REGBELONG;
  --
  ALTER TABLE PEADMIN.T_PERSONAL DROP  CONSTRAINT FK_PERSONAL_PARTY ;
  DROP TABLE T_PSN_PARTY;
  --
  ALTER TABLE PEADMIN.T_PERSONAL DROP CONSTRAINT FK_PERSONAL_GRADE ;
  DROP TABLE T_PSN_GRADE;
  --
  ALTER TABLE PEADMIN.T_PERSONAL DROP CONSTRAINT FK_PERSONAL_SCHOOLING ;
  DROP TABLE T_PSN_SCHOOLING;
  --
  ALTER TABLE PEADMIN.T_PERSONAL DROP CONSTRAINT FK_PERSONAL_SPEC ;
  DROP TABLE T_PSN_SPEC;
  --
  ALTER TABLE PEADMIN.T_PERSONAL DROP CONSTRAINT FK_PERSONAL_DEGREE ;
  DROP TABLE T_PSN_DEGREE;
  --
  ALTER TABLE PEADMIN.T_PERSONAL DROP CONSTRAINT FK_PERSONAL_GRADUATE;
  DROP TABLE T_PSN_GRADUATE;
  --
